### ISSUE TITLE
Voice drops on hblink

### ISSUE THREAD

**Issue by Jean-Marc-F1SCA** [n0mjs710/hblink3#14]
Hi,

We have found voice drops (groups of 4 voice loss of about 300ms each) which are synchronized with the REPORT_INTERVAL of the section [REPORT] in hblink.cfg. So for a report interval of 10s, voice drops occur every 10s. The actual workaround is to set the report interval to 180s, but it has effects on the dashboard.

**Comment by n0mjs710** [comment]
Using with program? hblink.py, bridge.py, playback.py, bridge_all.py?
What type of system is it running on? Processor? RAM? 
What else is running on the system? What's the load when this occurs, etc.? 
Are any errors showing up in the log(s) at the time of drops?

This suite of software is entirely built on an asynchronous I/O "reactor" model, with timed callbacks for housekeeping functions. Scaling often has to do with available resources and the speed with which tasks are dispatched. Before considering something else is going on, you need to demonstrate that there are no resource contentions on your system.

**Comment by n0mjs710** [comment]
I strongly recommend not running HBmonitor on the same server unless you are assured that it is executed on a different core than bridge.py is. Python will only be able to use a single processing core for a given instance of the interpreter, so multiple cores don't matter.

The number of systems is inconsequential compared to the number of endpoints being serviced. How many total devices are connected and handling traffic when the problem shows up?

If this is a cloud-hosted server, unless the virtualized instance is absolutely guaranteed the resources listed, and the VM is given a high priority, it's very difficult to profile what's actually available.

I'd like to know if anyone running a larger install on a bare-metal system, and not running hbmonitor or anything else on the same system is having any issues.

**Comment by Jean-Marc-F1SCA** [comment]
The problem occurs with at least two devices, on the same instance of hblink

**Comment by n0mjs710** [comment]
No enough information provided, dozens of systems unable to reproduce.
