### ISSUE TITLE
config

### ISSUE THREAD

**Issue by iddq** [n0mjs710/hblink3#15]
can you please include default configs?

**Comment by n0mjs710** [comment]
There's not really a "default" configuration because every system is different. For example, what good would a default Radio ID be when they all must be unique? SAMPLE configurations are provided with the word SAMPLE in all capitals in the name.

**Comment by iddq** [comment]
If I got this error: ... is not a valid configuration file! 
What does it mean? the file exists and wrong or the file is missing?

**Comment by n0mjs710** [comment]
This is not a support form. This is for issues with the code. Try actually reading some of the documentation – like the README.md file that explains where to get help in the first paragraph. Do not post more support questions here.
