### ISSUE TITLE
HBLink3 and errors :Unrecognized command. Raw HBP PDU

### ISSUE THREAD

**Issue by sp2ong** [n0mjs710/hblink3#2]
Hi,

I have run HBLink as Master server and connect mmdvm hotspot but in log are:

ERROR 2019-05-17 12:28:04,942 (MASTER) Unrecognized command. Raw HBP PDU: b'4d4d44564d486f7374'
ERROR 2019-05-17 12:29:04,952 (MASTER) Unrecognized command. Raw HBP PDU: b'4d4d44564d486f7374'

What do they mean?

**Comment by n0mjs710** [comment]
I just means HBlink doesn't understand the command received. That most often happens when you get the password wrong.

**Comment by casper14209** [comment]
Greetings,
I'm also receiving the same error but only when I key up on the repeater. It shows that authentication was successful with both repeater-1 and master-1. 

Recommendations?

INFO 2019-10-14 21:03:53,052 (REPEATER-1) Sending login request to master 74.91.118.251:62031
INFO 2019-10-14 21:03:53,063 (REPEATER-1) Repeater Login ACK Received with 32bit ID: 122555948
INFO 2019-10-14 21:03:53,077 (REPEATER-1) Repeater Authentication Accepted
INFO 2019-10-14 21:03:53,077 (REPEATER-1) Repeater Configuration Sent
INFO 2019-10-14 21:03:53,090 (REPEATER-1) Repeater Configuration Accepted
INFO 2019-10-14 21:03:53,090 (REPEATER-1) Connection to Master Completed
INFO 2019-10-14 21:03:58,562 (MASTER-1) Repeater Logging in with Radio ID: 310535, 73.41.71.153:38483
INFO 2019-10-14 21:03:58,563 (MASTER-1) Sent Challenge Response to 310535 for login: 3928858087
INFO 2019-10-14 21:03:58,592 (MASTER-1) Peer 310535 has completed the login exchange successfully
INFO 2019-10-14 21:03:58,622 (MASTER-1) Peer b'KM6IRY  ' (310535) has sent repeater configuration
ERROR 2019-10-14 21:04:06,852 (MASTER-1) Unrecognized command. Raw HBP PDU: b'444d52410004bd072fbc6b004c4b4d36495259'
ERROR 2019-10-14 21:04:07,577 (MASTER-1) Unrecognized command. Raw HBP PDU: b'444d52410004bd072fbc6b004c4b4d36495259'
^CINFO 2019-10-14 21:04:12,453 (GLOBAL) SHUTDOWN: HBLINK IS TERMINATING WITH SIGNAL 2
INFO 2019-10-14 21:04:12,456 (GLOBAL) SHUTDOWN: DE-REGISTER SYSTEM: MASTER-1
INFO 2019-10-14 21:04:12,456 (MASTER-1) De-Registration sent to Peer: b'KM6IRY  ' (310535)
INFO 2019-10-14 21:04:12,457 (GLOBAL) SHUTDOWN: DE-REGISTER SYSTEM: REPEATER-1
INFO 2019-10-14 21:04:12,457 (REPEATER-1) De-Registration sent to Master: 74.91.118.251:62031
INFO 2019-10-14 21:04:12,458 (GLOBAL) SHUTDOWN: ALL SYSTEM HANDLERS EXECUTED - STOPPING REACTOR

**Comment by Eszartek** [comment]
4d4d44564d486f7374 is hex for "MMDVMHost"
444d52410004bd072fbc6b004c4b4d36495259 is hex for "DMRA....KM6IRY"
They are information packets, not command packets, nothing you need to worry yourself about.

**Comment by sp2ong** [comment]
Thank you for hint about HEX to ASCII convert info :-)

**Comment by casper14209** [comment]
Copy that. Thanks for the info.
