### ISSUE TITLE
A tool to management hblink3 server

### ISSUE THREAD

**Issue by sp2ong** [n0mjs710/hblink3#9]
Cort
We could use a tool for local communication with the HBlink3 server that would allow, for example, disable / enable defined rules without having to restart the server. Restart disconnects all links. Perhaps such a tool would allow restarting only the selected peers link without restarting the server

**Comment by n0mjs710** [comment]
Sure. When I happen to have an extra 100 hours of development time, I'll do a core re-write to include this.
